05_DJango/04_STATIC/boards/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='boards'

urlpatterns = [
    path('',views.index, name="index"),
    path('registerfrm/', views.registerfrm, name="registerfrm"),
    path('register/', views.register, name="register"),
    path('detail/<int:pk>', views.detail, name="detail"),
    path('delete/<int:pk>', views.delete, name="delete"),
    path('updatefrm/<int:pk>', views.updatefrm, name="updatefrm"),
    path('update/<int:pk>', views.update, name="update"),
]

05_DJango/04_STATIC/fourthpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

05_DJango/04_STATIC/boards/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to="") #글 입력시 이미지 로딩 안해도 상관없다
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

05_DJango/04_STATIC/boards/views.py
from django.shortcuts import render, redirect

#추가
from . models import Board

# Create your views here.
def index(request):
    #boards = Board.objects.all()
    board_all = Board.objects.order_by('-pk')
    context={
        'boards':board_all
    }
    return render(request, "boards/index.html" , context)

def registerfrm(request):
    return render(request, "boards/registerfrm.html")


def register(request):
    title = request.POST.get('title')
    content= request.POST.get('content')
    
    #추가하기
    try:
        image = request.FILES['image']
    except:
        image = None
        
    board = Board(title=title, content = content, image = image)
    board.save()
    
    #templates가 아닌 url로 요청을 다시 보내는 랜더링 방법.. redirect
    #return render(request, "boards/register.html")
    return redirect('boards:index')

def detail(request, pk):
    board = Board.objects.get(pk=pk)
    
    context={
        'board':board
    }
    return render(request, "boards/detail.html" , context)

def delete(request, pk):
    board = Board.objects.get(pk=pk)

    if request.method=="POST":
        board.delete()
        return redirect('boards:index')

    else:
        return redirect('boards:detail', board.pk)

def updatefrm(request, pk):
    board = Board.objects.get(pk=pk)
    context = {
        'board':board
    }

    return render(request, "boards/updatefrm.html", context)

def update(request, pk):
    board = Board.objects.get(pk=pk) #수정되기전
    
    #수정폼에 입력된 값을 아래서 받아온다...수정됨
    board.title = request.POST.get('title')
    board.content = request.POST.get('content')
    board.save()
    return redirect('boards:detail', pk)

05_DJango/04_STATIC/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>상세 글 보기</h2>
  <ul>
    <li>글제목
      {{board.title}}</li>
    <li>글내용
      {{board.content}}</li>
    <li>글 처음 쓴 시각
      {{board.created_at}}</li>
    <li>글 수정한 시각
      {{board.updated_at}}</li>
  </ul>
  <p></p>

  {% if board.image %}
    <img src="{{board.image.url}}" alt="" width="200px" height="200px">
  {% endif %}
  <p></p>

  <a href="{% url 'boards:index' %}">[INDEX]</a>
  <form action="{% url 'boards:delete' board.pk%}" method="post">
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
  </form>

  <a href="{% url 'boards:updatefrm' board.pk%}">UPDATE</a>
{% endblock content %}

05_DJango/04_STATIC/boards/templates/boards/index.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
{% comment %} <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}"> {% endcomment %}
{% endblock css %}


{% block content %}
  <div class="jumbotron">
    <h2 align="center">Boards Model Data</h2>
  </div>

  <img src="{% static 'boards/images/write.png' %}" alt="" width="200px" height="200px">

  <p></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>TITLE</th>
        <th>CONTENT</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            {{board.pk}}
          </td>
          <td>
            <a href="{% url 'boards:detail' board.pk%}">{{board.title}}</a>
          </td>
          <td>
            {{board.content}}
          </td>
        </tr>

      {% endfor %}
    </tbody>

  </table>

  <a href="{% url 'boards:registerfrm' %}">[글쓰기]</a>

{% endblock content %}

05_DJango/04_STATIC/boards/templates/boards/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>게시글이 작성되었습니다.</h2>
{% endblock content %}

<a href="{% url 'boards:index' %}">[INDEX]</a>

05_DJango/04_STATIC/boards/templates/boards/registerfrm.html
{% extends 'base.html' %}

{% block content %}
<h2 align='center'>Register Form</h2>
<div align='center'>
    <form action="{% url 'boards:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
        TITLE <input type="text" name="title"><p></p>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
        <p></p>

        Image <input type="file" name="image">
        <p></p>
        <hr>
        
        <input type="tel">
        <input type="number">
        <input type="email">
        <input type="url">
        <input type="password">
        <input type="text">
        <input type="range">
        
        <hr>
        <input type="submit" value="Register">
    </form>
</div>

<a href="{% url 'boards:index' %}">[INDEX]</a>
</fieldset>
{% endblock content %}

05_DJango/04_STATIC/fourthpjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
    {% block css %}{% endblock css %}
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
      <a class="navbar-brand" href="#">Logo</a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
    </nav>

    <div class="container" style="margin-top:80px">

      {% block content %}{% endblock content %}

    </div>
  </body>

</html>